require "pp"
require "time"
require "thor"
require "hirb"
require "hirb-unicode"

require "climine/redmine"
require "climine/config"
require "climine/template"
require "climine/command/base"
require "climine/command/config"
require "climine/command/issue"
require "climine/command/user"
require "climine/command/project"
require "climine/command/tracker"
require "climine/command/status"

class Climine::CLI < Thor
  register Climine::Command::Config, :init, "init", "intialize config"
  register Climine::Command::Issue, :issue, "issue [COMMAND]", "subcommands for issue"
  register Climine::Command::User, :user, "user [COMMAND]", "subcommands for user"
  register Climine::Command::Project, :project, "project [COMMAND]", "subcommands for project"
  register Climine::Command::Tracker, :tracker, "tracker [COMMAND]", "subcommands for tracker"
  register Climine::Command::Status, :status, "status [COMMAND]", "subcommands for status"
end
